version: '3.8'

services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: 'contefin'
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=${DOMAIN}
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro

  lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: 'contenima'
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=contefin
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'api-container'
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_URI: ${DB_URI}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
