name: Docker CI/CD

on:
  push:
    branches:
      - master 

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build Docker Image
      run: docker build -t orlando333/dockerhubfin:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push orlando333/dockerhubfin:latest

  notify:
    name: Notify Pipeline Status
    runs-on: ubuntu-latest
    needs: build-and-push  

    steps:
    - name: Notify via GitHub
      run: echo "Docker Image built and pushed successfully!"  
