name: Terraform CI/CD

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_DO_Token: ${{ secrets.DO_Token }}       
  TF_VAR_MONGO_URI: ${{ MONGO_URI }}    
  TF_VAR_MONGO_DB: ${{ MONGO_DB }}        
  TF_VAR_DOMAIN: ${{ DOMAIN }}           
  TF_VAR_USER_EMAIL: ${{ secrets.USER_EMAIL }}   
  TF_VAR_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  TF_VAR_SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Create SSH keys from secrets
        run: |
          mkdir -p keys
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/orlando_server
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./keys/orlando_server.pub
          chmod 600 ./keys/orlando_server
          chmod 644 ./keys/orlando_server.pub

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt 

      - name: Terraform validate
        run: terraform validate 

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply --auto-approve
