name: Terraform CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_TOKEN }}
